---
- name: director playbook
  hosts: localhost
  
  tasks:
    - name: provision a vm
      vmware_guest:
        hostname: "{{ lookup('ini', 'vcenter_address section=director file=settings.ini')}}"
        username: "{{ lookup('ini', 'vcenter_user section=director file=settings.ini') }}"
        password: "{{ lookup('ini', 'vcenter_pass section=director file=settings.ini') }}"
        validate_certs: no
        name: "{{ lookup('ini', 'vm_name section=director file=settings.ini') }}"
        template: "{{ lookup('ini', 'vm_template section=director file=settings.ini') }}"
        networks:
          - name: "{{ lookup('ini', 'vm_public_pg section=director file=settings.ini') }}"
            ip: "{{ lookup('ini', 'vm_public_ip section=director file=settings.ini') }}"
            netmask: "{{ lookup('ini', 'vm_public_netmask section=director file=settings.ini') }}"
            gateway: "{{ lookup('ini', 'vm_public_gw section=director file=settings.ini') }}"
          - name: "{{ lookup('ini', 'vm_private_pg section=director file=settings.ini') }}"
            ip: "{{ lookup('ini', 'vm_private_ip section=director file=settings.ini') }}"
            netmask: "{{ lookup('ini', 'vm_public_netmask section=director file=settings.ini') }}"
        customization:
          hostname: "{{ lookup('ini', 'vm_hostname section=director file=settings.ini') }}"
          password: "{{ lookup('ini', 'vm_password section=director file=settings.ini') }}"
        state: present
      tag: ['provision']

    - name: power on the vm
      vmware_guest:
        hostname: "{{ lookup('ini', 'vcenter_address section=director file=settings.ini')}}"
        username: "{{ lookup('ini', 'vcenter_user section=director file=settings.ini') }}"
        password: "{{ lookup('ini', 'vcenter_pass section=director file=settings.ini') }}"
        validate_certs: no
        name: "{{ lookup('ini', 'vm_name section=director file=settings.ini') }}"
        state: poweredon
        wait_for_ip_address: yes
      delegate_to: localhost
      tags: ['provision']

    - name: remove the vm
      vmware_guest:
        hostname: "{{ lookup('ini', 'vcenter_address section=director file=settings.ini')}}"
        username: "{{ lookup('ini', 'vcenter_user section=director file=settings.ini') }}"
        password: "{{ lookup('ini', 'vcenter_pass section=director file=settings.ini') }}"
        validate_certs: no
        name: "{{ lookup('ini', 'vm_name section=director file=settings.ini') }}"
        state: absent
      tags: ['teardown']

- name: initialize director
  hosts: director

  tasks:
    - name: prepare a crypted password
      command: mkpasswd --method=sha-512 {{ lookup('ini', 'vm_password section=director file=settings.ini') }}
      register: mkpasswd_out

    - name: add user stack
      user:
        name: stack
        password: "{{ mkpasswd_out.stdout }}"

