---
- hosts: director
  vars_files: 
    - var/main.yaml

  tasks:
    - name: install overcloud images
      become: true
      yum: 
        name={{ item }} state=present
      with_items: 
        - rhosp-director-images
        - rhosp-director-images-ipa

    - name: untar and upload images
      vars: 
        version: "{{ lookup('ini', 'image_version section=overcloud file=settings.ini') }}"
      become: yes
      become_user: stack
      shell: |
        for i in /usr/share/rhosp-director-images/overcloud-full-latest-{{ version }}.tar \
        /usr/share/rhosp-director-images/ironic-python-agent-latest-{{ version }}.tar; \
        do tar -xvf $i -C /home/stack/images; done
        source /home/stack/stackrc
        openstack overcloud image upload --image-path /home/stack/images/
      tags:
        - untar

    - name: Get neutron subnet uuid
      shell: |
        source /home/stack/stackrc
        neutron subnet-list -c id -f value
      register: neutron_subnet_uuid

    - debug: msg="neutron_subnet_uuid is {{ neutron_subnet_uuid.stdout }}"

    - name: setup nameserver for undercloud neutron subnet
      shell: |
        source /home/stack/stackrc
        neutron subnet-update {{ neutron_subnet_uuid.stdout }} \
        --dns-nameserver 8.8.8.8
    
    - name: Get instackenv.json
      template:
        src: templates/instackenv.json.j2
        dest: /home/stack/instackenv.json
        owner: stack
        group: stack
        mode: '644'
      tags:
        - instack

    - name: Import instackenv.json
      shell: . /home/stack/stackrc; openstack baremetal import --json /home/stack/instackenv.json
      tags:
        - ironic
     
    - name: assign kernel and ramdisk images to all nodes and set nodes to managable state
      shell: |
        source /home/stack/stackrc
        openstack baremetal configure boot
        for node in $(openstack baremetal node list -c UUID -f value) ; do openstack baremetal node manage $node ; done
        openstack overcloud node introspect --all-manageable --provide
      tags:
        - introspect

#    - name: start hardware introspect
#      os_ironic_inspect:
#        auth_type: password
#        auth:
#          auth_url: http://192.168.3.1:5000/v2.0
#          username: admin
#          password: dangerous
#          project_name: admin 
#        name: "lxh11ser6"
#        #http://docs.ansible.com/ansible/os_ironic_inspect_module.html
#      tags:
#        - introspect

    - name: tagging node into profiles
      shell: 
        openstack baremetal node set --property capabilities='profile:compute,boot_option:local' 58c3d07e-24f2-48a7-bbb6-6843f0e8ee13

    - name: customerize network-environment.yaml
      template: 
        src: templates/network-environment.yaml.j2
        dest: /home/stack/templates/network-environment.yaml
        owner: stack
        group: stack
        mode: '644'

    - name: customerize nic-configs
      template:
        src: templates/nic-configs/{{ item }}.j2
        dest: /home/stack/tempaltes/nic-configs/{{ item }}.yaml
      with_items:
        - controller
        - compute

    - name: deploy overcloud
      shell:
        openstack overcloud deploy --templates \
        -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml \
        -e /home/stack/templates/network-environment.yaml \
        --control-flavor control --compute-flavor compute \
        --ntp-server 10.254.67.22 --neutron-network-type vxlan --neutron-tunnel-types vxlan

