---
- hosts: director
  vars_files: 
    - var/main.yaml

  tasks:
    - name: install overcloud images
      become: true
      yum: 
        name={{ item }} state=present
      with_items: 
        - rhosp-director-images
        - rhosp-director-images-ipa
      tags:
        - image

    - name: untar and upload images
      vars: 
        version: "{{ lookup('ini', 'image_version section=overcloud file=settings.ini') }}"
      become: yes
      become_user: stack
      shell: |
        for i in /usr/share/rhosp-director-images/overcloud-full-latest-{{ version }}.tar \
        /usr/share/rhosp-director-images/ironic-python-agent-latest-{{ version }}.tar; \
        do tar -xvf $i -C /home/stack/images; done
        source /home/stack/stackrc
        openstack overcloud image upload --image-path /home/stack/images/
      tags:
        - untar

    - name: Get neutron subnet uuid
      shell: |
        source /home/stack/stackrc
        neutron subnet-list -c id -f value
      register: neutron_subnet_uuid
      tags:
        - uuid

    - debug: msg="neutron_subnet_uuid is {{ neutron_subnet_uuid.stdout }}"
      tags:
        - print

    - name: setup nameserver for undercloud neutron subnet
      shell: |
        source /home/stack/stackrc
        neutron subnet-update {{ neutron_subnet_uuid.stdout }} \
        --dns-nameserver 8.8.8.8
      tags:
        - dns
    
    - name: Get instackenv.json
      template:
        src: templates/instackenv.json.j2
        dest: /home/stack/instackenv.json
        owner: stack
        group: stack
        mode: '644'
      tags:
        - instack

    - name: Import instackenv.json
      shell: . /home/stack/stackrc; openstack overcloud node import /home/stack/instackenv.json
      tags:
        - ironic
     
    - name: assign kernel and ramdisk images to all nodes and start introspect
      shell: |
        source /home/stack/stackrc
        openstack baremetal configure boot
        for node in $(openstack baremetal node list -c UUID -f value) ; do openstack baremetal node manage $node ; done
        openstack overcloud node introspect --all-manageable --provide
      tags:
        - introspect

    - name: tagging node into profiles and defind local_gb, root_device
      shell: | 
        source /home/stack/stackrc
        openstack baremetal node set --property capabilities='profile:control,boot_option:local' {{ host1_name }}
        openstack baremetal node set --property capabilities='profile:compute,boot_option:local' {{ host2_name }}
        openstack baremetal node set --property root_device='{"serial":"600605b0098d2330212400a8177b2d41"}' {{ host1_name }}
        openstack baremetal node set --property root_device='{"serial":"600605b0098e98001c82dd295cd95e90"}' {{ host2_name }}
        openstack baremetal node set --property local_gb='{"283"}' {{ host1_name }}
        openstack baremetal node set --property local_gb='{"283"}' {{ host2_name }}
      tags:
        - tag

    - name: create directory nic-configs
      shell:
        mkdir /home/stack/templates/nic-configs
        mkdir /home/stack/templates/nic-configs/bond-with-vlans
      become: yes
      become_user: stack
      become_method: su
      tags:
        - mkdir

    - name: customerize network-environment.yaml
      template: 
        src: templates/network-environment.yaml.j2
        dest: /home/stack/templates/network-environment.yaml
        owner: stack
        group: stack
        mode: '644'
      tags:
        - temp1

    - name: customerize nic-configs
      template:
        src: templates/nic-configs/bond-with-vlans/{{ item }}.yaml.j2
        dest: /home/stack/templates/nic-configs/bond-with-vlans/{{ item }}.yaml
        owner: stack
        group: stack
        mode: '644'
      with_items:
        - controller
        - compute
      tags:
        - temp2

    - name: copy run-os-net-config.sh to template folder
      shell:
        cp /usr/share/openstack-tripleo-heat-templates/network/scripts/run-os-net-config.sh /home/stack/templates
      become: yes
      become_user: stack
      become_method: su
      tags:
        - temp3

    - name: deploy overcloud
      shell: |
        source /home/stack/stackrc
        openstack overcloud deploy --templates \
        -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml \
        -e /home/stack/templates/network-environment.yaml \
        --control-flavor control --compute-flavor compute \
        --ntp-server 10.254.67.22 >> /home/stack/overcloud_status.txt
      become: yes
      become_user: stack
      become_method: su
      tags:
        - deploy
